# Site settings
title: Associazione Italiana Studenti di Fisica
description: Sito in costruzione, un po' di pazienza
banner: img/banner.png
# url: "http://yourdomain.com" # the base hostname & protocol for your site
destination: ../site/
timezone: Europe/Rome
locale: "it"

# Build settings
markdown: kramdown

#facebook
fb_admins: 
fb_appid:

#Collections
collections:
- events
- events_local
