# Site settings
title: Associazione Italiana Studenti di Fisica
description: Sito in costruzione, un po' di pazienza
# url: "http://yourdomain.com" # the base hostname & protocol for your site
destination: ../site/

# Build settings
markdown: kramdown

#additional gems wanted by the css icons, goddammit
gems: [bourbon, neat]
